import item1 from "./assets/Item1.png";
import item2 from "./assets/Item2.png";
import item3 from "./assets/Item3.png";
import item4 from "./assets/Item4.png";
import item5 from "./assets/Item5.png";
import item6 from "./assets/Item6.png";

export const ItemMenu = [
  {
    id: 1,
    thumbImg: item1,
    listImg: [item1, item3, item4, item5],
    category: ["burger", "break fast", "fast food", "junk food"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Burger",
    price: "$12.00",
  },
  {
    id: 2,
    thumbImg: item2,
    listImg: [item2, item3, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Chicken Chup",
    price: "$18.00",
  },
  {
    id: 3,
    thumbImg: item3,
    listImg: [item3, item1, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Pizza",
    price: "$15.00",
  },
  {
    id: 4,
    thumbImg: item4,
    listImg: [item4, item3, item6, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Chocolate Muffin",
    price: "$21.00",
  },
  {
    id: 5,
    thumbImg: item5,
    listImg: [item5, item3, item4, item1],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Sandwiches",
    price: "$12.00",
  },
  {
    id: 6,
    thumbImg: item6,
    listImg: [item6, item3, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Fresh Lime",
    price: "$12.00",
  },
  {
    id: 7,
    thumbImg: item1,
    listImg: [item1, item3, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Burger",
    price: "$12.00",
  },
  {
    id: 8,
    thumbImg: item2,
    listImg: [item2, item3, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Chicken Chup",
    price: "$18.00",
  },
  {
    id: 9,
    thumbImg: item3,
    listImg: [item3, item6, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Pizza",
    price: "$15.00",
  },
  {
    id: 10,
    thumbImg: item4,
    listImg: [item4, item3, item2, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Chocolate Muffin",
    price: "$21.00",
  },
  {
    id: 11,
    thumbImg: item5,
    listImg: [item5, item3, item4, item2],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Sandwiches",
    price: "$12.00",
  },
  {
    id: 12,
    thumbImg: item6,
    listImg: [item6, item3, item4, item5],
    category: ["burger", "breakfast", "fastfood", "junkfood"],
    rating: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque diam pellentesque bibendum non dui volutpat fringilla bibendum. Urna, urna, vitae feugiat pretium donec id elementum. Ultrices mattis sed vitae mus risus. Lacus nisi, et ac dapibus sit eu velit in consequat.",
    name: "Fresh Lime",
    price: "$12.00",
  },
];
